### PR TITLE
1) Related Services Widget Created

### PR DESCRIPTION
**Pull request by MuhammadHassanAmin**
1) Related Services Widget Created
2) Badges Component Created

### CODE REVIEW

**Comment by dukefoss** [comment]
When I try out the site in the branch category-related-services the Explore-page doesnt work and the categories doesnt show. Is this PR not ready?

**Comment by MuhammadHassanAmin** [comment]
> When I try out the site in the branch category-related-services the Explore-page doesnt work and the categories doesnt show. Is this PR not ready?

can you please check now and verify I mistakenly committed with local URL

**Comment by dukefoss** [comment]
I cant get the "Explore" page to work

**Comment by MuhammadHassanAmin** [comment]
> I cant get the "Explore" page to work

please check now

**Pull request merged**
