### PR TITLE
updated the home page and how this works page

### PR DESCRIPTION
**Pull request by AmmarMasood**
Redesigned the landing page and how this works page.

### CODE REVIEW

**Comment by dukefoss** [comment]
The categories does not appear on this branch. Is this an issue or will it be fixed when merging the branch into development-test?

**Comment by oddaspa** [comment]
@AmmarMasood There seems to be a build error due to node-sass or gyp. I could not fix it, can you try?

**Comment by AmmarMasood** [comment]
> The categories does not appear on this branch. Is this an issue or will it be fixed when merging the branch into development-test?

Hi, the categories were missing in the development-test branch too even before I started working on it. I thought another developer is working on some features. If that's not the case I can fix that just lmk. Thanks.

**Comment by AmmarMasood** [comment]
> @AmmarMasood There seems to be a build error due to node-sass or gyp. I could not fix it, can you try?

Hi the issue does not seem to be happening on my end, can you please check if you have this node-sass version "^4.14.1" installed.

**Comment by dukefoss** [comment]
> too even before I started working on it. I thought another developer is working on some features. If that's not the case I can fix that just lmk. Thanks.

I see! Then it should be no problem:)

**Comment by dukefoss** [comment]
> > @AmmarMasood There seems to be a build error due to node-sass or gyp. I could not fix it, can you try?
> 
> Hi the issue does not seem to be happening on my end, can you please check if you have this node-sass version "^4.14.1" installed. Also please check out this:
> 
> https://stackoverflow.com/questions/45589179/npm-install-throwing-error-in-node-sass
> 
> maybe try and update the node-sass version, can be helpful.

I think oddaspa is talking about the checks within the github build, not the local build on our pc. Could it maybe work to update the node-sass version within this branch? @AmmarMasood @oddaspa

**Pull request merged**
